### ISSUE TITLE
Raspberry pi armv6hf

### ISSUE THREAD

**Issue by iyedb** [freebsd/crochet#139]
Not sure is the right place to ask or if it's even an issue but why raspberry pi board config does not set TARGET_ARCH to armv6hf? Why isn't it armv6hf by default.

**Comment by kientzle** [comment]
Please send us a pull request with your suggested change.

**Comment by iyedb** [comment]
#140 :)

**Comment by zif2016** [comment]
can I add linux_base-c6 into RPi2 IMG?

**Comment by kientzle** [comment]
You can try.

Step 1:  See if linux_base-c6 actually works on RPi2.  You should build and RPi2 image and try installing the package to see if it works (the FreeBSD port and package tools all work on RPi2).  If not, work with the FreeBSD developers to find out what would be needed to get it to work.

Step 2: Crochet has some experimental support for installing packages during the image creation.  They are documented in config.sample.sh.  They do not work for all packages because some packages cannot be cross-installed (the FreeBSD teams working on package support would like to support cross-installing more packages).

Step 3:  Let us know how it works for you.

**Comment by zif2016** [comment]
I can't  get linux_base-c6 src in FreeBSD-arm v11 on RPi2. so that I never to make install it。

**Comment by brd** [comment]
Closing.

For package installing see #141.
